### ISSUE TITLE
Issue with getting rank

### ISSUE THREAD

**Issue by wald0040** [Darkflame72/asyncpixel#564]
Hello there.

This might be a very stupid question, but i am reletively new to coding, so i am in need of a little help.
I am writing this as a bug report because i had no idea where else to submit it.

I am trying to get the rank of players, by using "player.rank", however i have noticed that if a player has a speciel rank like owner or admin, or if they have had mvp++ in the past but now has mvp+. "player.rank" returns "ON", instead of giving the actual rank.

**Comment by Darkflame72** [comment]
That does seem to be a bug so I'll have a look into it sorry about that. Just to make sure I fix all the bugs what players are you testing with?

**Comment by Darkflame72** [comment]
Hey that's not a stupid question it actually seems like you have found a bug. I'll take a look into it and get it all fixed for you, to make sure I completely fix it what players have you tested?

**Comment by wald0040** [comment]
> Hey that's not a stupid question it actually seems like you have found a bug. I'll take a look into it and get it all fixed for you, to make sure I completely fix it what players have you tested?

Hello, thanks for the quick reply.
I havent tested lots of players, but i have tested Hypixel, a few admins, and then some random mvp+ accounts including my own, which has had mvp++ in the past.

**Comment by wald0040** [comment]
Another little add, i just tested it on some youtube ranks, and they seem to be returning "ON" aswell.

**Comment by Darkflame72** [comment]
@all-contributors please add @wald0040 for bugs
