### ISSUE TITLE
Duplicate argument 'buy_summary' in BazaarItem constructor

### ISSUE THREAD

**Issue by MillionthOdin16** [Darkflame72/asyncpixel#670]
Hi there, I noticed that in the BazaarItem constructor, there is a duplicate argument for "buy_summary". The second argument should actually be "sell_summary". This fixes the documentation, which is otherwise great!

```
class BazaarItem(BaseModel):
    """Bazaar item.
    Args:
        product_id (str): Product id.
    --> buy_summary (List[BazaarSellSummary]): List of sell summary.
        buy_summary (List[BazaarBuySummary]): List of buy summary.
        quick_status (BazaarQuickStatus): Quick status.
    """
```

Awesome job, and I really appreciate the lib!

https://github.com/Darkflame72/asyncpixel/blob/68074ca00e72cba22db09099bf3894a5677f3dc1/asyncpixel/models/bazaar.py#LL65

**Comment by Darkflame72** [comment]
@all-contributors please add @MillionthOdin16 for bugs

**Comment by Darkflame72** [comment]
This is fixed in the latest version of the docs
