### ISSUE TITLE
skyblock/auctions requires an api key, but it is not needed

### ISSUE THREAD

**Issue by ch-iv** [Darkflame72/asyncpixel#687]
**Describe the bug**
Requesting the /skyblock/auction endpoint without an api key raises an `InvalidApiKeyError`.
 
**To Reproduce**
```python
async def main():
    hypixel = asyncpixel.Hypixel(api_key=None)
    print(await hypixel.auctions())
    await hypixel.close()

asyncio.run(main())
```
Error:
```
asyncpixel.exceptions.exceptions.InvalidApiKeyError: No API key provided
```

**Expected behavior**
The endpoint in question does not require an api key. The code should work without providing a key.

**Comment by ch-iv** [comment]
There is the same issue with /skyblock/bazaar

If this is unintentional, I can submit a PR with a fix

**Comment by Darkflame72** [comment]
This is unintentional so feel free to raise a PR, thanks for finding this. 

@all-contributors please add @ch-iv for bugs
